# Generated by Django 4.0.1 on 2022-01-31 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('classroom', models.CharField(max_length=65)),
                ('exam_duration', models.IntegerField()),
                ('teacher_name', models.CharField(max_length=65)),
                ('type_of_exam', models.CharField(choices=[('Descriptive', 'descriptive'), ('Test', 'test'), ('T/F', 't/f')], max_length=20)),
                ('exam_url', models.URLField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
