# Generated by Django 4.0.1 on 2022-02-07 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_alter_question_answer_stuqs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StuQs',
            new_name='StudentAnswer',
        ),
    ]
