# Generated by Django 4.0.1 on 2022-02-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_rename_stuqs_studentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='qs_score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
