# Generated by Django 4.0.1 on 2022-02-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_question_qs_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_score',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
